require 'plugins.gruvbox-material'
require 'plugins.icon'
require 'plugins.which-key'
require 'plugins.mini'
require 'plugins.todo-comments'
require 'plugins.telescope'
require 'plugins.fidget'
-- require 'plugins.lint'
require 'plugins.autopairs'
require 'plugins.neo-tree'
require 'plugins.gitsigns'
